agricultural_waste_biogas_words = [
    "manure", "compost", "slurry", "silage", "straw", "chaff", "husk", "stubble", "biomass", "methane",
    "fertilizer", "digester", "fermentation", "anaerobic", "sludge", "organic", "decomposition", "biodegradable", "microbes", "bacteria",
    "greenhouse", "renewable", "sustainable", "byproduct", "nutrient", "carbon", "nitrogen", "phosphorus", "ammonia", "volatile",
    "feedstock", "substrate", "digestion", "biogas", "biofuel", "energy", "electricity", "heat", "cogeneration", "waste",
    "crop", "livestock", "farm", "agriculture", "rural", "tank", "reactor", "pipeline", "storage", "treatment",
    "odor", "smell", "gas", "combustion", "engine", "generator", "turbine", "boiler", "burner", "flare",
    "temperature", "pressure", "moisture", "pH", "acidity", "alkalinity", "retention", "residence", "time", "mixing",
    "stirring", "pumping", "loading", "unloading", "transport", "collection", "separation", "sorting", "shredding", "grinding",
    "chopping", "crushing", "screening", "filtering", "drying", "composting", "recycling", "reuse", "recovery", "disposal",
    "landfill", "incineration", "pollution", "contamination", "leachate", "runoff", "emission", "odor", "control", "treatment",
    "purification", "filtration", "scrubbing", "desulfurization", "deodorization", "upgrading", "enrichment", "compression", "storage", "distribution",
    "pipeline", "grid", "injection", "utilization", "consumption", "efficiency", "optimization", "monitoring", "automation", "control",
    "sensor", "meter", "valve", "pipe", "fitting", "seal", "gasket", "flange", "weld", "joint",
    "insulation", "coating", "corrosion", "protection", "safety", "risk", "hazard", "explosion", "fire", "leak",
    "detection", "alarm", "shutdown", "emergency", "maintenance", "repair", "inspection", "cleaning", "disinfection", "sterilization",
    "hygiene", "sanitation", "pathogen", "virus", "bacteria", "fungi", "parasite", "weed", "seed", "spore",
    "germination", "growth", "decay", "rot", "spoilage", "preservation", "conservation", "storage", "silo", "bin",
    "hopper", "conveyor", "auger", "elevator", "mixer", "blender", "separator", "centrifuge", "press", "extruder",
    "dryer", "cooler", "heater", "exchanger", "condenser", "evaporator", "absorber", "adsorber", "membrane", "filter",
    "screen", "sieve", "cyclone", "scrubber", "precipitator", "baghouse", "incinerator", "gasifier", "pyrolyzer", "carbonizer",
    "torrefier", "pelletizer", "briquetter", "baler", "wrapper", "packer", "palletizer", "stacker", "loader", "unloader",
    "truck", "tractor", "trailer", "wagon", "cart", "forklift", "crane", "hoist", "winch", "pulley",
    "belt", "chain", "gear", "motor", "pump", "compressor", "blower", "fan", "impeller", "rotor",
    "stator", "bearing", "shaft", "coupling", "clutch", "brake", "switch", "relay", "contactor", "controller",
    "inverter", "transformer", "capacitor", "resistor", "inductor", "fuse", "breaker", "battery", "charger", "regulator",
    "converter", "rectifier", "amplifier", "transmitter", "receiver", "antenna", "cable", "wire", "conduit", "junction",
    "terminal", "connector", "plug", "socket", "adapter", "surge", "protector", "grounding", "earthing", "lightning",
    "arrestor", "suppressor", "isolator", "disconnector", "interrupter", "recloser", "sectionalizer", "feeder", "busbar", "switchgear",
    "substation", "transformer", "generator", "alternator", "exciter", "governor", "synchronizer", "load", "demand", "supply",
    "consumption", "production", "capacity", "output", "input", "efficiency", "loss", "gain", "factor", "power",
    "energy", "voltage", "current", "frequency", "phase", "harmonics", "distortion", "fluctuation", "sag", "swell",
    "interruption", "outage", "blackout", "brownout", "flicker", "noise", "interference", "radiation", "electromagnetic", "compatibility",
    "shielding", "filtering", "damping", "absorption", "reflection", "refraction", "diffraction", "scattering", "attenuation", "amplification",
    "modulation", "demodulation", "encoding", "decoding", "encryption", "decryption", "authentication", "authorization", "access", "control",
    "security", "privacy", "confidentiality", "integrity", "availability", "reliability", "redundancy", "backup", "recovery", "restoration",
    "continuity", "resilience", "robustness", "flexibility", "scalability", "interoperability", "compatibility", "standardization", "certification", "compliance",
    "regulation", "legislation", "policy", "guideline", "standard", "code", "practice", "protocol", "procedure", "instruction",
    "manual", "handbook", "guide", "reference", "specification", "datasheet", "blueprint", "schematic", "diagram", "drawing",
    "model", "prototype", "sample", "test", "trial", "experiment", "analysis", "simulation", "calculation", "estimation",
    "prediction", "forecast", "projection", "trend", "pattern", "correlation", "causation", "effect", "impact", "consequence",
    "benefit", "cost", "value", "price", "market", "demand", "supply", "economics", "finance", "investment",
    "return", "profit", "loss", "revenue", "expense", "budget", "funding", "grant", "subsidy", "incentive",
    "tax", "credit", "deduction", "exemption", "rebate", "refund", "discount", "premium", "surcharge", "fee",
    "charge", "rate", "tariff", "quota", "limit", "cap", "threshold", "benchmark", "target", "goal",
    "objective", "strategy", "plan", "program", "project", "initiative", "action", "task", "activity", "operation",
    "process", "procedure", "method", "technique", "approach", "system", "framework", "structure", "organization", "management",
    "administration", "coordination", "collaboration", "cooperation", "partnership", "alliance", "network", "association", "federation", "consortium",
    "union", "league", "council", "committee", "board", "panel", "commission", "authority", "agency", "department",
    "division", "section", "unit", "team", "group", "community", "society", "public", "private", "government",
    "industry", "business", "company", "corporation", "enterprise", "firm", "institution", "organization", "establishment", "facility",
    "plant", "factory", "mill", "refinery", "laboratory", "workshop", "warehouse", "stockyard", "depot", "terminal",
    "port", "harbor", "dock", "wharf", "pier", "jetty", "berth", "quay", "marina", "shipyard",
    "drydock", "slipway", "ramp", "platform", "scaffold", "gantry", "crane", "derrick", "hoist", "winch",
    "pulley", "tackle", "rigging", "sling", "hook", "shackle", "clamp", "vise", "jack", "lift",
    "elevator", "escalator", "conveyor", "transporter", "vehicle", "truck", "trailer", "wagon", "cart", "trolley",
    "forklift", "pallet", "container", "bin", "drum", "tank", "vessel", "silo", "hopper", "bunker",
    "pit", "trench", "ditch", "channel", "canal", "pipeline", "conduit", "duct", "flume", "chute",
    "trough", "gutter", "drain", "sewer", "culvert", "manhole", "catchment", "basin", "reservoir", "dam",
    "weir", "spillway", "gate", "valve", "penstock", "turbine", "generator", "alternator", "motor", "engine",
    "compressor", "pump", "blower", "fan", "ventilator", "extractor", "separator", "filter", "strainer", "screen",
    "sieve", "cyclone", "centrifuge", "classifier", "sorter", "grader", "washer", "cleaner", "scrubber", "dryer",
    "cooler", "heater", "boiler", "furnace", "kiln", "oven", "incinerator", "reactor", "digester", "fermenter",
    "bioreactor", "crystallizer", "evaporator", "distiller", "condenser", "absorber", "adsorber", "exchanger", "recuperator", "regenerator",
    "accumulator", "collector", "concentrator", "separator", "extractor", "leacher", "precipitator", "settler", "clarifier", "thickener",
    "dewatering", "press", "centrifuge", "filter", "dryer", "granulator", "pelletizer", "extruder", "molder", "caster",
    "former", "shaper", "cutter", "slicer", "chopper", "grinder", "crusher", "pulverizer", "atomizer", "sprayer",
    "nozzle", "injector", "mixer", "blender", "homogenizer", "emulsifier", "disperser", "agitator", "stirrer", "kneader",
    "masticator", "compounder", "reactor", "polymerizer", "vulcanizer", "curer", "coater", "laminator", "calenderer", "embosser",
    "printer", "coder", "marker", "labeler", "packager", "wrapper", "sealer", "capper", "closer", "palletizer",
    "stacker", "unstacker", "loader", "unloader", "sorter", "picker", "placer", "assembler", "disassembler", "tester",
    "inspector", "grader", "classifier", "sorter", "separator", "cleaner", "washer", "dryer", "sterilizer", "pasteurizer",
    "cooker", "fryer", "roaster", "toaster", "brewer", "fermenter", "distiller", "blender", "mixer", "homogenizer",
    "emulsifier", "churner", "crystallizer", "granulator", "tablet", "capsule", "pill", "syrup", "solution", "suspension",
    "emulsion", "gel", "cream", "ointment", "lotion", "powder", "granule", "pellet", "flake", "fiber",
    "filament", "yarn", "thread", "fabric", "textile", "leather", "fur", "hide", "skin", "pelt",
    "feather", "wool", "hair", "bristle", "fiber", "pulp", "paper", "board", "film", "foil",
    "sheet", "plate", "bar", "rod", "wire", "tube", "pipe", "profile", "section", "beam",
    "girder", "column", "truss", "frame", "panel", "board", "plank", "timber", "lumber", "log",
    "pole", "post", "pile", "mat", "felt", "foam", "sponge", "rubber", "plastic", "resin",
    "polymer", "monomer", "oligomer", "elastomer", "thermoplastic", "thermoset", "composite", "ceramic", "glass", "metal",
    "alloy", "steel", "iron", "copper", "aluminum", "zinc", "lead", "tin", "nickel", "cobalt",
    "chromium", "manganese", "molybdenum", "tungsten", "titanium", "zirconium", "vanadium", "niobium", "tantalum", "hafnium",
    "rhenium", "osmium", "iridium", "platinum", "palladium", "rhodium", "ruthenium", "gold", "silver", "mercury",
    "cadmium", "indium", "gallium", "germanium", "silicon", "boron", "carbon", "graphite", "diamond", "fullerene",
    "nanotube", "graphene", "semiconductor", "insulator", "conductor", "superconductor", "piezoelectric", "thermoelectric", "photovoltaic", "electroluminescent",
    "phosphor", "scintillator", "laser", "maser", "fiber", "optic", "waveguide", "resonator", "cavity", "antenna",
    "transducer", "sensor", "detector", "emitter", "transmitter", "receiver", "transponder", "amplifier", "attenuator", "modulator",
    "demodulator", "multiplexer", "demultiplexer", "router", "switch", "hub", "repeater", "bridge", "gateway", "firewall",
    "server", "client", "workstation", "terminal", "console", "keyboard", "mouse", "monitor", "display", "projector",
    "printer", "scanner", "copier", "fax", "modem", "router", "switch", "hub", "repeater", "bridge",
    "gateway", "firewall", "server", "client", "workstation", "terminal", "console", "keyboard", "mouse", "monitor",
    "display", "projector", "printer", "scanner", "copier", "fax", "modem", "router", "switch", "hub",
    "repeater", "bridge", "gateway", "firewall", "server", "client", "workstation", "terminal", "console", "keyboard",
    "mouse", "monitor", "display", "projector", "printer", "scanner", "copier", "fax", "modem", "router",
    "switch", "hub", "repeater", "bridge", "gateway", "firewall", "server", "client", "workstation", "terminal",
    "console", "keyboard", "mouse", "monitor", "display", "projector", "printer", "scanner", "copier", "fax",
    "modem", "router", "switch", "hub", "repeater", "bridge", "gateway", "firewall", "server", "client"
]

def checking(query):
    flag = False
    list_of_words = query.split(" ")
    for i in list_of_words:
        for j in agricultural_waste_biogas_words:
            if i in j.lower().split(" "):
                flag = True
                break
    return flag